meso-network/meso-js

.changeset/config.json
.changeset/tame-carpets-explain.md
packages/meso-js/package.json
packages/post-message-bus/package.json
packages/types/package.json
pnpm-lock.yaml

With the `0.0.61` release, a bug was introduced that made `@meso-network/types` unavailable when pulling from the registry. This fixes that issue and also ensures packages are made public.

ensure meso-js and post-message-bus are published as public packages

---

.changeset/tricky-eels-notice.md
packages/post-message-bus/package.json
packages/post-message-bus/src/index.ts
packages/post-message-bus/src/types.ts
pnpm-lock.yaml

This removes the types dependency from post-message-bus.

fix: remove types dependency from post-message-bus

---

.changeset/hip-geckos-compare.md
packages/meso-js/README.md
packages/meso-js/test/validateTransferConfiguration.test.ts
packages/types/src/index.ts

This removes the testnet options from the `transfer` configuration. Currently, only mainnet configuration is supported and this caused confusion in our sandbox environments.

Remove testnets

---

.changeset/serious-lamps-judge.md
packages/meso-js/README.md
packages/meso-js/src/transfer.ts
packages/meso-js/src/validateTransferConfiguration.ts
packages/meso-js/test/frame.test.ts
packages/meso-js/test/transfer.test.ts
packages/meso-js/test/validateTransferConfiguration.test.ts
packages/types/src/index.ts

For partners using embedded wallets, message signing or the existence of a wallet itself may be transparent to the end user. In this scenario, it may not make sense for the user to be prompted to trigger message signing to either verify wallet ownership or approve a transaction.
To support this scenario, you can launch the Meso experience with the `headlessSignature` param set to `true`. In doing so, the `onSignMessageRequest` callback will be immediately invoked when needed, allowing you to return a signed message back to the Meso SDK using the embedded wallet and keeping this step completely transparent to the user. Once the signed message is received, the rest of the Meso experience proceeds as usual.

add support for headless message signing

---

.changeset/config.json
.changeset/red-seas-juggle.md

Update changeset config to mark all modules as fixed, not linked. Per [the docs](https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md):
Fixed packages allow you to specify a group or groups of packages that should be versioned and published together. Unlike linked packages, all packages in the group of fixed packages will be version-bumped and published together even when there are no changes done to some of the the member packages.
Linked packages will still only be bumped when there is a changeset for them (this can mean because you explicitly choose to add a changeset for it or because it's a dependent of something being released).

fixed changeset

---

.changeset/metal-jars-travel.md
packages/meso-js/README.md
packages/meso-js/src/bus.ts
packages/meso-js/src/validateTransferConfiguration.ts
packages/meso-js/test/bus.test.ts
packages/meso-js/test/validateTransferConfiguration.test.ts
packages/post-message-bus/src/types.ts
packages/post-message-bus/src/validators.ts
packages/post-message-bus/test/validators.test.ts
packages/types/src/index.ts

Ahead of launching support for additional networks and assets, we are introducing more precise errors for unsupported networks/assets.

add unsupported network/asset error

---

.changeset/lemon-toys-breathe.md
packages/post-message-bus/src/createPostMessageBus.ts
packages/post-message-bus/test/setupTests.ts

Previously, we were using only [`ancestorOrigins`](https://developer.mozilla.org/en-US/docs/Web/API/Location/ancestorOrigins) which is unsupported in [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Location/ancestorOrigins#browser_compatibility).
This PR introduces a fallback lookup mechanism using [`document.referrer`](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer).

fix(@meso-network/post-message-bus): 🐛 safely lookup parent origins across browsers 

---

.changeset/serious-points-provide.md
packages/post-message-bus/src/createPostMessageBus.ts

If there is no document.referrer (meaning we are in the top frame), the URL constructor will error out. This allows us to gracefully ignore a missing referrer.
This is a follow-up to #21.

fix(@meso-network/post-message-bus): introduce guard when looking up document.referrer

---

.changeset/clean-guests-work.md
packages/meso-js/README.md
packages/meso-js/src/transfer.ts
packages/meso-js/test/factories/index.ts
packages/meso-js/test/frame.test.ts
packages/meso-js/test/transfer.test.ts
packages/types/src/index.ts

This deprecates `headlessSignature` in favor of a new configuration parameter – `authenticationStrategy`.
The `authenticationStrategy` allows the following values:
- `WALLET_VERIFICATION` – Requires the user to sign a message with their wallet before engaging in a transfer
- `HEADLESS_WALLET_VERIFICATION` – Requires an app (such as an embedded wallet) to sign a message on behalf of the user
- `NO_WALLET_VERIFICATION` – Requires no wallet signing for the transfer. This is typically used for pre-deployed smart contract wallets
After the rollout, we will fully remove `headlessSignature` in a future version.

feat(@meso-network/meso-js): :sparkles: introduce authenticationStrategy configuration option

---

packages/meso-js/CHANGELOG.md
packages/post-message-bus/CHANGELOG.md
packages/types/CHANGELOG.md

We accidentally referenced the wrong `AuthenticationStrategy` enum value. `NO_WALLET_VERIFICATION` should read `BYPASS_WALLET_VERIFICATION`
This is a follow up to #25

docs: fix release notes

---

.changeset/khaki-ladybugs-work.md
packages/meso-js/src/index.ts

As a follow-up to #29, this ensures `createPostMessageBus` is exported for use within transfers.

feat(@meso-network/meso-js): export createPostMessageBus

---

.changeset/nice-walls-rescue.md
packages/meso-js/src/createPostMessageBus.ts
pnpm-lock.yaml

In the case where iframes are on the page and we attempt to read their `src` attribute, our check blows up. This guards against unreadable frame sources.

fix(@meso-network/meso-js): 🐛 guard against checking unreadable iframes

---

.changeset/sharp-rats-cry.md
packages/meso-js/src/transfer.ts
packages/meso-js/src/types.ts
packages/meso-js/src/validateTransferConfiguration.ts
packages/meso-js/test/factories/index.ts
packages/meso-js/test/frame.test.ts
packages/meso-js/test/transfer.test.ts
packages/meso-js/test/validateTransferConfiguration.test.ts

This is a follow up to https://github.com/meso-network/meso-js/pull/25.

feat(@meso-network/meso-js): 🔥 remove deprecated headlessSignature option in favor of `authenticationStrategy`

---

.changeset/pink-planets-clap.md
packages/meso-js/src/frame.ts
packages/meso-js/test/frame.test.ts

This allows the meso iframe to render the correct background color(s) when the embedding page overrides the os/browser level color scheme.

feat(@meso-network/meso-js): ✨ add color-scheme style attribute to iframe by default

---

.changeset/breezy-poets-lay.md
packages/meso-js/src/createPostMessageBus.ts
packages/meso-js/src/parseMessage.ts
packages/meso-js/src/result.ts
packages/meso-js/src/transfer.ts
packages/meso-js/src/types.ts
packages/meso-js/test/createPostMessageBus.test.ts
packages/meso-js/test/factories/index.ts
packages/meso-js/test/frame.test.ts
packages/meso-js/test/parseMessage.test.ts
packages/meso-js/test/transfer.test.ts

This allows the Meso experience to operate in the context of native mobile applications via webviews as well as traditional browser iframes.
A new configuration parameter (`mode`) has been introduced. It will default to `embedded`, but also supports a value of `webview`. I am _intentionally_ not documenting this for now (though it is documented in the type system).
This PR updates "postMessageBus" to accept a second argument (a synthetic window) which, if provided, will be used as a target to send messages to from within the Meso experience.
It also adds logic around the handling of messages since we cannot guarantee that they will always be objects. Instead, we parse out the structured objects from strings (if necessary) and then process the message(s).

feat(@meso-network/meso-js): ⚡ extend message bus to accept webview window references

---

.changeset/neat-onions-watch.md
packages/meso-js/src/createPostMessageBus.ts

This introduces additional checks in our post messaging library to see if we are in a WebView context and also check for React Native specific injected `postMessage` capabilities.
The [react-native-webview](https://github.com/react-native-webview/react-native-webview/tree/master) library has a convention of injecting a `window.ReactNativeWebView` namespace into the running application to negotiate post messaging.
In the future, we may find it makes more sense to allow the handle to the `postMessage` function to be passed to us at initialization time, but I think the trade-off of specificity – _for now_ – is acceptable.

feat(@meso-network/meso-js): ✨ allow post messaging with React Native webview contexts

---

.changeset/nice-days-sell.md
cspell.json
packages/meso-js/README.md
packages/meso-js/src/types.ts
packages/meso-js/test/validateTransferConfiguration.test.ts

This enables Arbitrum support via the `Network` type.

feat(@meso-network/meso-js): ✨ Enable Arbitrum support

---

.changeset/hungry-bugs-play.md
packages/meso-js/README.md
packages/meso-js/src/bus.ts
packages/meso-js/src/types.ts

This will allow developers to hook into a `READY` event when the iframe is loaded. Having this functionality will help in orchestrating rendering/revealing the Meso frame in embedding applications.

feat(@meso-network/meso-js): ✨ Introduce READY event for when iframe is loaded

---

.changeset/slimy-parents-kneel.md
packages/meso-js/src/validators.ts
packages/meso-js/test/validators.test.ts

This fixes a bug introduced in #49.

fix(@meso-network/meso-js): 🐛 Ensure READY event is added to message validation

---

.changeset/serious-squids-admire.md
package.json
packages/meso-js/src/bus.ts
packages/meso-js/src/transfer.ts
packages/meso-js/src/types.ts
packages/meso-js/src/validateTransferConfiguration.ts
packages/meso-js/src/validators.ts
packages/meso-js/test/bus.test.ts
packages/meso-js/test/factories/index.ts
packages/meso-js/test/frame.test.ts
packages/meso-js/test/transfer.test.ts
packages/meso-js/test/validateTransferConfiguration.test.ts
packages/meso-js/test/validators.test.ts

Support cash-outs by expanding the `transfer` API, which now supports a `destinationAsset` value of `Asset.USD` and an optional `onSendTransactionRequest` callback.

add support for cash outs

---

.github/workflows/release.yaml

This will address the warning that we are out of date on each CI run

chore(@meso-network): :arrow_down: Bump actions/checkout and actions/setup-node to v4

---

.changeset/neat-points-report.md
pnpm-lock.yaml

This is an attempt to fix our failing CI builds which are causing the `ERR_PNPM_GIT_UNCLEAN` error to surface. Admittedly, we aren't sure what the exact problem is, but this re-runs `pnpm i` with the `--fix-lockfile` flag which fixes "broken" lockfile entries ([docs](https://pnpm.io/cli/install#--fix-lockfile)).

run pnpm --fix-lockfile

---

.changeset/wild-ducks-try.md
packages/meso-js/src/inlineTransfer.ts

This prevents a bug where if a developer called `destroy()` and the reference to the modal onboarding frame was lost, our logic would throw an undue exception.

fix(@meso-network/meso-js): :goal_net: guard against missing frame when unmounting sibling iframes in the inline integration

---

.changeset/new-pens-raise.md
packages/meso-js/src/types.ts

This allows us to have another signal when dismissing modal onboarding in the inline integration

feat(@meso-network/meso-js): add ONBOARDING_TERMINATED type to inline frame actions

---

.changeset/nasty-pets-shave.md
packages/meso-js/src/inlineTransfer.ts
packages/meso-js/src/types.ts

This adds the `TRANSFER_INCOMPLETE` event to the [`onEvent`](https://developers.meso.network/javascript-sdk/reference#on-event) callback.
This event is dispatched only for the `inlineTransfer` integration and signals the user was unable to complete onboarding due to KYC failures/restrictions. It is not the same as the user canceling the flow.

feat(@meso-network/meso-js): ✨ Add TRANSFER_INCOMPLETE to onEvent callback

---

packages/meso-js/CHANGELOG.md
packages/meso-js/src/types.ts

This amends the type-level documentation and CHANGELOG description for the `TRANSFER_INCOMPLETE` event released in 0.1.4.

docs(@meso-network/meso-js): Clarify TRANSFER_INCOMPLETE meaning

---

.changeset/cuddly-bats-watch.md
packages/meso-js/src/frame.ts
packages/meso-js/src/inlineTransfer.ts
packages/meso-js/src/types.ts
packages/meso-js/src/validators.ts
packages/meso-js/test/frame.test.ts
packages/meso-js/test/validators.test.ts

In order to support partner-specific settings (such as themes), we need to be able to pass configuration data to the modal onboarding frame that can be negotiated _before_ standing up the transfer application inside the iframe. This PR enables shuttling a `search` field with the `INITIATE_MODAL_ONBOARDING` event.

feat(@meso-network/meso-js): Allow passing query string to modal onboarding frame for the inline integration

---

.changeset/old-games-teach.md
cspell.json
packages/meso-js/src/frame.ts
packages/meso-js/test/frame.test.ts

For partners who have their referrer policy set to `no-referrer`, Meso's iframe is unable to load in Firefox due to `location.ancestorOrigins` also not being set in FireFox. In order to prevent this issue, we explicitly set the `referrerPolicy` on the iframe html node to `origin`.

explicitly set origin referrer policy on iframe

---

.changeset/good-shrimps-punch.md
packages/meso-js/src/frame.ts
packages/meso-js/test/frame.test.ts

There are issues where in partner applications, Meso modals may render below other highly z-indexed elements. This sets the `z-index` to `2147483647` which is the highest number allowed.
See [this thread](https://x.com/wesbos/status/1796201727529513377) for more, specifically, this [reply](https://x.com/wesbos/status/1796209959509578212):
> It’s the largest integer that fits in 32 bits, so it’s the highest z-index you can give something in CSS
**Note:** Migration to a `<dialog>` element is on the roadmap but we do not have a definitive timeline for its release.

feat(@meso-network/meso-js): 🚸 ensure modal iframes are rendered at the highest z-index

---

.changeset/large-keys-kneel.md
packages/meso-js/README.md
packages/meso-js/src/types.ts
packages/meso-js/test/validateConfiguration.test.ts

Polygon's MATIC token is now POL: https://polygon.technology/blog/save-the-date-matic-pol-migration-coming-september-4th-everything-you-need-to-know

feat(@meso-network/meso-js): :wastebasket: deprecate MATIC in favor of POL
